name: USTB Test CI

on:
  - pull_request

env:
  FOUNDRY_PROFILE: ci
  RPC_URL: ${{ secrets.RPC_URL }}

jobs:
  forge:
    strategy:
      fail-fast: true

    name: Run Forge Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Forge Dependencies
        run: forge install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
